services:
  upwork_enricher_app:
    build: .
    image: upwork_enricher:latest
    command: python3 ./src/orchestrator/scheduled_run.py
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24225
        tag: "upwork_enricher.app"
    depends_on:
      - fluentd

  fluentd:
    image: fluent/fluentd:v1.12.0-debian-1.0
    ports:
      - 23225:24225
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - ./logs:/fluentd/logs
