on:
  push:
    branches:
      - main
jobs:
  token-retriver-to-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Venv
        working-directory: src/authorizer
        run: pip install virtualenv

      - name: Activate Virtual ENV
        working-directory: src/authorizer
        run: python -m venv venv && source venv/bin/activate && pip install -r requirements.txt

      - name: Run Tests
        working-directory: src/authorizer
        env:
          ZYTE_KEY: ${{secrets.ZYTE_KEY}}
          POSTGREST_URL: ${{secrets.POSTGREST_URL}}
          SUPABASE_CLIENT_ANON_KEY: ${{secrets.SUPABASE_CLIENT_ANON_KEY}}
          AUTH_SECRET: ${{secrets.AUTH_SECRET}}
        run: . venv/bin/activate && python3 -m unittest

      - name: Create archive of dependencies
        working-directory: src/authorizer
        run: |
          cd ./venv/lib/python3.12/site-packages
          zip -r9 ../../../../token_retriver.zip .

      - name: Add SRC files to Zip file
        working-directory: src/authorizer
        run: cd ./src && zip -g ../token_retriver.zip -r .

      - name: Upload zip file artifact
        uses: actions/upload-artifact@v2
        with:
          name: token_retriver
          path: src/authorizer/token_retriver.zip

  token-retriver-to-aws:
    runs-on: ubuntu-latest
    needs: [token-retriver-to-zip]
    steps:
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Download token_retriver.zip
        uses: actions/download-artifact@v2
        with:
          name: token_retriver

      - name: Upload to s3
        run: aws s3 cp token_retriver.zip s3://asaniczka-upwork-job-scraper-lambda/token_retriver.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy new Lambda
        run: aws lambda update-function-code --function-name upwork_token_retriever --s3-bucket asaniczka-upwork-job-scraper-lambda --s3-key token_retriver.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
