on:
  push:
    branches:
      - main
jobs:
  token-retriver-to-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Venv
        working-directory: src/authorizer
        run: pip install virtualenv

      - name: Activate Virtual ENV
        working-directory: src/authorizer
        run: python -m venv venv && source venv/bin/activate && pip install -r requirements.txt

      - name: Run Tests
        working-directory: src/authorizer
        env:
          ZYTE_KEY: ${{secrets.ZYTE_KEY}}
          POSTGREST_URL: ${{secrets.POSTGREST_URL}}
          SUPABASE_CLIENT_ANON_KEY: ${{secrets.SUPABASE_CLIENT_ANON_KEY}}
          AUTH_SECRET: ${{secrets.AUTH_SECRET}}
        run: . venv/bin/activate && python3 -m unittest

      - name: Create archive of dependencies
        working-directory: src/authorizer
        run: |
          cd ./venv/lib/python3.12/site-packages
          zip -r9 ../../../../api.zip .

      - name: Add API files to Zip file
        working-directory: src/authorizer
        run: cd ./src && zip -g ../api.zip -r .

      - name: Upload zip file artifact
        uses: actions/upload-artifact@v2
        with:
          name: api
          path: src/authorizer/api.zip
